# ENDPOINT_PREFIX: /api
REQUIRED_ENDPOINTS:
  query:
    path: /prompt
    props:
      - query
      - context
    mime_type: multipart/form-data
  upload:
    path: /upload
    props:
      - files
      - context
  health:
    path: /health
    props: []
# SERVER_PORT: 8081
# CHROMA_PORT: 8000