# ENDPOINT_PREFIX: /api
REQUIRED_ENDPOINTS:
  query:
    path: /prompt
    props:
      - query
    mime_type: application/json
  upload:
    path: /upload
    props:
      - files
  health:
    path: /health
    props: []
